#!/bin/zsh
# @@PRODUCT@@ @@VERSION@@ — check the staged first release before committing it.
#
# GENERATED by scripts/make-first-release-check.sh in plugin-city-wp-test-harness.
# Do not hand-edit: regenerate instead, or the fault suite stops covering it.
#   generator version @@GENERATOR_VERSION@@
#
# Double-click this file, or run it from Terminal. It writes nothing and commits
# nothing. It reads the staged working copy and says PASS or STOP.
#
# What it is really checking: that all three parts of a first release go up
# together. The plugin in trunk/, the pinned copy in tags/@@VERSION@@/ and the
# listing pictures in assets/ are three separate things, and the pictures live
# outside the plugin, so they are the ones a first release forgets. Commit the
# readme without them and the listing shows captions for images that are not
# there.
#
# Run with --list-checks to print every check this script can fail, which is how
# the fault suite knows what it has to cover.

emulate -L zsh
setopt null_glob

WC="@@WC@@"
SLUG="@@SLUG@@"
VER="@@VERSION@@"
REPO_URL="@@REPO_URL@@"
ATTESTATION="@@ATTESTATION@@"

# ---------------------------------------------------------------------------
# Every check that can fail is declared here with a stable id. bad() refuses an
# id that is not in this list, so the declaration cannot drift away from the
# code, and --list-checks reads straight off it. The fault suite requires one
# injected fault per id, which is what stops a check from being added with
# nothing proving it refuses anything.
# ---------------------------------------------------------------------------
typeset -A CHECKS
CHECKS=(
  URL          "working copy points at the expected repository"
  TRUNK-EMPTY  "trunk/ has files staged"
  TAG-EMPTY    "tags/<version>/ has files staged"
  ASSETS-EMPTY "assets/ has pictures staged"
  STRAY        "no unversioned, missing or conflicted entries"
  MAINFILE     "main plugin file is at the top level of trunk/"
  WRAPPED      "plugin is not inside a second wrapping folder"
  README       "trunk/readme.txt exists"
  TAGDIFF      "trunk/ and the tag hold the same files"
  DOMAIN       "header Text Domain equals the directory slug"
  DOMAIN-CODE  "every translatable string names that domain"
  DOMAIN-LOAD  "load_plugin_textdomain() loads that domain"
  POT          "translation template is present and correctly named"
  POT-DOMAIN   "translation template X-Domain equals the slug"
  STABLE       "readme stable tag, header version and tag folder agree"
  CAP-ORPHAN   "every screenshot caption has a picture"
  SHOT-ORPHAN  "every picture has a caption"
  ART-MISSING  "required banner and icon are present"
  ART-SIZE     "artwork pixel size matches the size in its name"
  GBP          "nothing is priced in sterling in the text"
  ATTEST       "image attestation, when supplied, is complete and current"
  DEVFILES     "no development files, caches or paid code in trunk or the tag"
)
# Declared but deliberately not failable. Reported so an exemption is visible
# rather than silent.
typeset -A INFORMATIONAL
INFORMATIONAL=(
  UPSTREAM "whether the repository is empty, populated or unreachable — an empty answer and a failed connection are indistinguishable, so neither is treated as a verdict"
)

if [[ "$1" == "--list-checks" ]]; then
  for id in ${(k)CHECKS}; do print -- "$id"; done | sort
  for id in ${(k)INFORMATIONAL}; do print -- "$id informational"; done | sort
  exit 0
fi

fail=0
note() { print -- "  $1"; }
bad() {
  local id="$1"; shift
  if [[ -z "${CHECKS[$id]}" ]]; then
    print -- "  INTERNAL ERROR: undeclared check id '$id'. Regenerate this script."
    exit 2
  fi
  print -- "  ** [$id] $1"
  fail=1
}

# Pixel size read out of the PNG header rather than with sips, so this works on
# a Mac and in CI. PNG puts width and height as big-endian 32-bit values at
# offsets 16 and 20, after the signature and the IHDR length and type.
png_dim() {
  local f="$1"
  local -a b
  b=( ${(z)"$(od -An -tu1 -j16 -N8 -- "$f" 2>/dev/null)"} )
  if (( ${#b} != 8 )); then print -- "unreadable"; return 1; fi
  local w=$(( b[1] * 16777216 + b[2] * 65536 + b[3] * 256 + b[4] ))
  local h=$(( b[5] * 16777216 + b[6] * 65536 + b[7] * 256 + b[8] ))
  print -- "${w}x${h}"
}

is_png() {
  [[ "$(od -An -c -N4 -- "$1" 2>/dev/null | tr -d ' ')" == *'211PNG'* ]]
}

print -- ""
print -- "@@PRODUCT@@ $VER — staged first release"
print -- "=============================================="
print -- "Working copy: $WC"
print -- ""

if [[ ! -d "$WC/.svn" ]]; then
  print -- "STOP: no SVN working copy at that path. Nothing to check."
  read "?Press return to close. " 2>/dev/null
  exit 1
fi
cd "$WC" || exit 1

# ------------------------------------------------------- the right repository
print -- "1. Is this the right repository, and is it really a first release?"
url=$(svn info --show-item url 2>/dev/null | tr -d '[:space:]')
if [[ "$url" == "$REPO_URL" ]]; then
  note "yes — $url"
else
  bad URL "unexpected URL: $url"
  bad URL "expected $REPO_URL"
fi

upstream=$(svn list -R "$REPO_URL" 2>/dev/null)
if (( $? == 0 )); then
  committed=$(print -r -- "$upstream" | grep -v '/$' | grep -c .)
  if (( committed == 0 )); then
    note "nothing is committed upstream yet, so this is the first release."
  else
    note "$committed file(s) already committed upstream — read section 2 carefully."
  fi
else
  note "could not reach the repository, so this is UNKNOWN."
  note "an empty answer and a failed connection look identical, so neither is"
  note "being treated as 'first release'. Nothing below depends on this."
fi
print -- ""

# --------------------------------------------------- all three parts, one go
print -- "2. Are all three parts staged, and nothing else?"
svnst=$(svn status)
added=(${(f)"$(print -r -- $svnst | grep '^A')"})
other=(${(f)"$(print -r -- $svnst | grep -v '^A' | grep -v '^$')"})

a_trunk=$(print -r -- $svnst | grep -c '^A.*trunk/')
a_tag=$(print -r -- $svnst | grep -c "^A.*tags/$VER")
a_assets=$(print -r -- $svnst | grep -c '^A.*assets/.*\.\(png\|svg\|jpg\)')

note "entries scheduled for addition: ${#added}"
note "  under trunk/ ........ $a_trunk"
note "  under tags/$VER/ .... $a_tag"
note "  pictures in assets/ . $a_assets"

(( a_trunk > 0 ))  || bad TRUNK-EMPTY "trunk/ is empty. There is no plugin to release."
(( a_tag > 0 ))    || bad TAG-EMPTY "tags/$VER/ is empty. The directory would serve an unpinned version."
(( a_assets > 0 )) || bad ASSETS-EMPTY "assets/ has no pictures. The readme's captions would name nothing."

if (( a_trunk > 0 && a_tag > 0 && a_assets > 0 )); then
  note "all three are in this one commit, which is the point."
fi

if (( ${#other} == 0 )); then
  note "no missing, conflicted or unversioned files."
else
  bad STRAY "unexpected entries — an unversioned file will NOT be committed:"
  print -r -- ${(F)other} | sed 's/^/     /'
fi
print -- ""

# ------------------------------------------------ trunk is not double-wrapped
print -- "3. Is the plugin at the top level of trunk/, not inside a folder?"
# Located by its header rather than by its filename: the two can differ, and a
# brand-stripped submission archive is the proof — a product-expiry-dates/
# folder holding plugincity-product-expiry-dates.php.
mainfile=""
for f in trunk/*.php; do
  if grep -qE '^[[:space:]]*\*?[[:space:]]*Plugin Name:' "$f" 2>/dev/null; then
    mainfile="$f"; break
  fi
done
if [[ -n "$mainfile" ]]; then
  note "yes — $mainfile carries the Plugin Name header, directly in trunk/."
else
  bad MAINFILE "no file in trunk/ carries a Plugin Name header."
  nested=$(find trunk -mindepth 2 -maxdepth 2 -name '*.php' \
           -exec grep -lE '^[[:space:]]*\*?[[:space:]]*Plugin Name:' {} \; 2>/dev/null | head -3)
  if [[ -n "$nested" ]]; then
    bad WRAPPED "found it one level down instead — the plugin is wrapped in a second folder:"
    print -r -- "$nested" | sed 's/^/     /'
    bad WRAPPED "WordPress would install a folder inside a folder and see no plugin."
  fi
fi
if [[ -f trunk/readme.txt ]]; then
  note "trunk/readme.txt is present; the listing is built from it."
else
  bad README "trunk/readme.txt is missing. The listing is built from it."
fi
print -- ""

# ------------------------------------------------------ trunk matches the tag
print -- "4. Do trunk/ and tags/$VER/ hold exactly the same files?"
if [[ ! -d "tags/$VER" ]]; then
  note "there is no tags/$VER to compare — see section 2."
elif diff -r trunk "tags/$VER" >/dev/null 2>&1; then
  note "identical, so the pinned version is the version trunk describes."
else
  bad TAGDIFF "trunk/ and tags/$VER/ differ:"
  diff -rq trunk "tags/$VER" 2>&1 | sed 's/^/     /'
fi
print -- ""

# -------------------------------------------- text domain is the directory slug
print -- "5. Does the text domain equal the directory slug?"
if [[ -n "$mainfile" ]]; then
  td=$(grep -m1 -E '^[[:space:]]*\*?[[:space:]]*Text Domain:' "$mainfile" \
       | sed 's/.*Text Domain:[[:space:]]*//' | tr -d '[:space:]')
  note "header Text Domain: ${td:-(none)}"
  note "directory slug:     $SLUG"
  if [[ "$td" == "$SLUG" ]]; then
    note "they match, so WordPress.org translations will load."
  else
    bad DOMAIN "they differ. Translations from WordPress.org would silently never load."
  fi
else
  bad DOMAIN "cannot read a Text Domain without a main plugin file."
fi

i18n='\b(__|_e|_x|_n|_nx|_ex|esc_html__|esc_html_e|esc_html_x|esc_attr__|esc_attr_e|esc_attr_x)\('
total=$(grep -rhoE "$i18n" trunk --include='*.php' 2>/dev/null | grep -c .)
wrong=$(grep -rnE "$i18n" trunk --include='*.php' 2>/dev/null | grep -v "$SLUG")
note "translatable strings in the code: $total"
if [[ -z "$wrong" ]]; then
  note "every one of them names $SLUG."
else
  bad DOMAIN-CODE "these translatable strings do not name $SLUG, so they would never translate:"
  print -r -- "$wrong" | sed 's/^/     /' | head -20
fi

loadline=$(grep -rA2 -h 'load_plugin_textdomain' trunk --include='*.php' 2>/dev/null)
if [[ -z "$loadline" ]]; then
  bad DOMAIN-LOAD "nothing calls load_plugin_textdomain(), so no translation is ever loaded."
elif print -r -- "$loadline" | grep -q "'$SLUG'"; then
  note "load_plugin_textdomain() loads '$SLUG', the same domain."
else
  bad DOMAIN-LOAD "load_plugin_textdomain() does not load '$SLUG'."
fi

pot="trunk/languages/$SLUG.pot"
if [[ -f "$pot" ]]; then
  note "template is filed as $SLUG.pot, the name WordPress looks for."
  xd=$(grep -m1 'X-Domain:' "$pot" \
       | sed -e 's/.*X-Domain:[[:space:]]*//' -e 's/\\n.*//' -e 's/"//g' -e 's/[[:space:]]*$//')
  if [[ "$xd" == "$SLUG" ]]; then
    note "and it agrees: X-Domain: $xd"
  else
    bad POT-DOMAIN "the .pot says X-Domain: '$xd', not '$SLUG'."
  fi
else
  bad POT "$pot is missing, so there is no translation template to ship."
fi
print -- ""

# ------------------------------------------------ stable tag matches the header
print -- "6. Does the stable tag match the plugin version?"
st=$(grep -m1 '^Stable tag:' trunk/readme.txt 2>/dev/null | sed 's/Stable tag:[[:space:]]*//' | tr -d '[:space:]')
hv=""
[[ -n "$mainfile" ]] && hv=$(grep -m1 -E '^[[:space:]]*\*?[[:space:]]*Version:' "$mainfile" \
       | sed 's/.*Version:[[:space:]]*//' | tr -d '[:space:]')
note "readme Stable tag: ${st:-(none)}"
note "plugin header:     ${hv:-(none)}"
note "tag folder:        tags/$VER"
if [[ "$st" == "$VER" && "$hv" == "$VER" && -d "tags/$VER" ]]; then
  note "all three agree on $VER."
else
  bad STABLE "these must all read $VER, or the directory serves the wrong version."
fi
print -- ""

# ----------------------------------------------- captions pair with real files
print -- "7. Does every screenshot caption have a picture to point at?"
caps=(${(f)"$(sed -n '/^== Screenshots ==/,/^== [A-Z]/p' trunk/readme.txt 2>/dev/null | grep -E '^[0-9]+\.')"})
shots=(assets/screenshot-*.png assets/screenshot-*.jpg)
note "captions in the readme: ${#caps}"
note "pictures in assets/:    ${#shots}"

for c in "${caps[@]}"; do
  n=${c%%.*}
  if [[ -f "assets/screenshot-$n.png" || -f "assets/screenshot-$n.jpg" ]]; then
    note "  $n. picture present"
  else
    bad CAP-ORPHAN "caption $n has no assets/screenshot-$n picture. The listing shows a gap."
  fi
done

for s in "${shots[@]}"; do
  n=${${s##*screenshot-}%.*}
  print -r -- ${(F)caps} | grep -qE "^$n\." \
    || bad SHOT-ORPHAN "assets/$(basename $s) has no caption, so it is published unexplained."
done

if (( ${#caps} == ${#shots} )) && (( ${#caps} > 0 )); then
  note "counts match, and every number pairs both ways."
fi
print -- ""

# --------------------------------------------------------- banners and icons
print -- "8. Are the banner and icon there, at the sizes WordPress.org uses?"
# 772x250 is the banner the directory actually draws and an icon is always shown,
# so those are required. The 1544x500 banner and the 256px icon are the high-DPI
# variants and are optional. An SVG icon is allowed and has no pixel size.
icon_found=""
for i in assets/icon-128x128.png assets/icon-256x256.png assets/icon.svg; do
  [[ -f "$i" ]] && icon_found="$icon_found $(basename $i)"
done
if [[ -n "$icon_found" ]]; then
  note "icon present:$icon_found"
else
  bad ART-MISSING "no icon in assets/. The listing falls back to a grey block."
fi
if [[ -f assets/banner-772x250.png ]]; then
  note "banner-772x250.png present (the one the directory draws)."
else
  bad ART-MISSING "assets/banner-772x250.png is missing."
fi
for opt in banner-1544x500 icon-256x256; do
  [[ -f "assets/$opt.png" ]] && note "$opt.png present (high-DPI, optional)."
done

for f in assets/banner-*.png assets/icon-*.png; do
  base=$(basename "$f" .png)
  want=${base##*-}
  [[ "$want" == *x* ]] || continue
  if ! is_png "$f"; then
    bad ART-SIZE "$(basename $f) is not a PNG despite its name."
    continue
  fi
  got=$(png_dim "$f")
  if [[ "$got" == "$want" ]]; then
    note "$(basename $f) — $got, correct."
  else
    bad ART-SIZE "$(basename $f) is $got, but its name promises $want."
  fi
done
print -- ""

# ------------------------------------------------------------- the currency
print -- "9. Is anything priced in sterling?"
r=$(grep -c '£' trunk/readme.txt 2>/dev/null)
code=$(grep -rl '£' trunk --include='*.php' --include='*.js' --include='*.css' 2>/dev/null)
note "£ in trunk/readme.txt: $r"
if (( r == 0 )) && [[ -z "$code" ]]; then
  note "none in the readme or the shipped code."
else
  bad GBP "sterling found in the text. If the pictures are in dollars they now disagree."
  [[ -n "$code" ]] && print -r -- "$code" | sed 's/^/     /'
fi

# This script cannot read an image. Rather than assert something about the
# pictures, it verifies an attestation if one was supplied: a list of the sums
# somebody actually looked at. Recapturing an image then invalidates the
# attestation instead of silently outdating a claim hardcoded here.
note "this script reads text only — it cannot see what is in a picture."
if [[ -z "$ATTESTATION" ]]; then
  note "NO IMAGE ATTESTATION was supplied, so nothing here has been checked"
  note "against the pictures. Somebody must open them."
elif [[ ! -f "$ATTESTATION" ]]; then
  bad ATTEST "attestation file not found: $ATTESTATION"
else
  stale=0; missing=0
  while read -r sum name rest; do
    [[ -z "$sum" || "$sum" == \#* ]] && continue
    if [[ ! -f "assets/$name" ]]; then
      bad ATTEST "attested picture assets/$name is not staged."; missing=1; continue
    fi
    actual=$(shasum -a 256 "assets/$name" | cut -d' ' -f1)
    if [[ "$actual" != "$sum" ]]; then
      bad ATTEST "assets/$name has changed since it was read. Attestation is stale."
      stale=1
    fi
  done < "$ATTESTATION"
  for s in "${shots[@]}"; do
    grep -q " $(basename $s)\( \|$\)" "$ATTESTATION" \
      || { bad ATTEST "assets/$(basename $s) is staged but nobody attested reading it."; missing=1; }
  done
  if (( stale == 0 && missing == 0 )); then
    note "every staged picture is attested as read, and none has changed since:"
    sed 's/^/     /' "$ATTESTATION" | grep -v '^     *$' | head -20
  fi
fi
print -- ""

# -------------------------------------------------- nothing private going up
print -- "10. Is anything going up that should not?"
junk=()
for pat in '.git' '.github' 'vendor' 'tests' 'composer.json' 'composer.lock' \
           'phpcs.xml.dist' 'phpstan.neon.dist' 'phpstan-bootstrap.php' \
           '.phpstan-cache' '.DS_Store' 'node_modules' '.wordpress-org' \
           '*.map' '.editorconfig'; do
  found=$(find trunk "tags/$VER" -name "$pat" 2>/dev/null)
  [[ -n "$found" ]] && junk+=("$found")
done
if (( ${#junk} == 0 )); then
  note "no development files, hidden folders or caches in trunk/ or the tag."
else
  bad DEVFILES "these do not belong in a released plugin:"
  print -r -- ${(F)junk} | sed 's/^/     /'
fi
print -- ""

# ------------------------------------------------------------------- verdict
print -- "=============================================="
if (( fail )); then
  print -- "STOP — do not commit. See the ** lines above."
  print -- ""
  print -- "Each ** line carries the id of the check that refused, so it can be"
  print -- "looked up and so the fault suite can prove that check works."
else
  print -- "PASS — safe to commit. Run exactly this, from anywhere:"
  print -- ""
  print -- "  cd $WC"
  print -- "  svn commit --username @@SVN_USER@@ \\"
  print -- "    -m \"@@PRODUCT@@ $VER: first release, with tags/$VER and listing assets\""
  print -- ""
  print -- "Your username is already saved, so it should only ask for your"
  print -- "WordPress.org password. If it says the repository is read-only,"
  print -- "commit access has not activated yet — wait and run this again."
  print -- ""
  print -- "No file names after 'svn commit'. Naming paths is how the pictures"
  print -- "get left behind and the listing ends up with captions for nothing."
fi
print -- "=============================================="
print -- ""
read "?Press return to close. " 2>/dev/null
exit $fail
